package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/sergioc0sta/server-graphql/graph/model"
)

// Courses is the resolver for the courses field.
func (r *categoryResolver) Courses(ctx context.Context, obj *model.Category) ([]*model.Courses, error) {
	courses, err := r.CourseDB.FindByCategory(obj.ID)
	if err != nil {
		return nil, err
	}

	var coursesModel []*model.Courses

	for _, course := range courses {
		coursesModel = append(coursesModel, &model.Courses{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}
	return coursesModel, nil
}

// Category is the resolver for the category field.
func (r *coursesResolver) Category(ctx context.Context, obj *model.Courses) (*model.Category, error) {
	category, err := r.CategoryDB.FindByCourseID(obj.ID)
	if err != nil {
		return nil, err
	}
	return &model.Category{
		ID: category.ID,
		Name: category.Name,
		Description: &category.Description,
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	category, err := r.CategoryDB.Creat(input.Name, *input.Description)
	if err != nil {
		return &model.Category{}, err
	}

	return &model.Category{
		ID:          category.ID,
		Description: &category.Description,
		Name:        category.Name,
	}, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCouse) (*model.Courses, error) {
	course, err := r.CourseDB.Create(input.Name, *input.Description, input.CategoryID)

	if err != nil {
		return nil, err
	}

	return &model.Courses{
		ID:          course.ID,
		Name:        course.Name,
		Description: &course.Description,
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.CategoryDB.FindAll()

	if err != nil {
		return nil, err
	}

	var categoriesModel []*model.Category

	for _, categorie := range categories {
		categoriesModel = append(categoriesModel, &model.Category{
			ID:          categorie.ID,
			Name:        categorie.Name,
			Description: &categorie.Description,
		})
	}

	return categoriesModel, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Courses, error) {
	courses, err := r.CourseDB.FindAll()
	if err != nil {
		return nil, err
	}

	var coursesModel []*model.Courses
	for _, course := range courses {
		coursesModel = append(coursesModel, &model.Courses{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}

	return coursesModel, nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Courses returns CoursesResolver implementation.
func (r *Resolver) Courses() CoursesResolver { return &coursesResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type categoryResolver struct{ *Resolver }
type coursesResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
